version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  bulid-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
workflows:
  build-and-test:
    jobs:
      - bulid-and-test